before_script:
  - npm i -g firebase-tools
  - npm install

include:
  - flask_server/.gitlab-ci.yml

deploy-functions:
  stage: deploy
  script:
    - cd react-app
    - npm run build
    - cd ..
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    refs:
      - master
