image: current-alpine3.18

stages:
  - lint
  - test
  - build
  - deploy
  - deploy-functions

before_script:
  - npm ci -g firebase-tools
  - npm ci

include:
  - flask_server/.gitlab-ci.yml

Linting:
  stage: lint
  script:
    - echo "linting..."

Tests:
  stage: test
  script:
    - echo "testing..."

Deploy:
  stage: deploy
  script:
    - firebase deploy
  only:
    refs:
      - master
    changes:
      - src/**/*

deploy-functions:
  stage: deploy-functions
  script:
    - cd react-app
    - npm run build
    - cd ..
    - firebase deploy --only functions
  only:
    refs:
      - master
    changes:
      - functions/**/*
