image: python:3.11-slim

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Linting:
  stage: lint
  script:
    - poetry run ruff check

Tests:
  stage: test
  script:
    - poetry run pytest

Deploy:
  stage: deploy
  script:
    - echo "deployed"

